# This file is part of OpenScan-Hardware
# Copyright 2023 OpenScan Contributors
# SPDX-License-Identifier: CC-BY-SA-4.0

title: OpenScan Hardware
author: OpenScan Contributors
copyright: "2023"

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/openscan-lsm/OpenScan-Hardware
  path_to_book: book
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
